<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Account extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	private $data_role = array(
		"2c282814-d165-4625-8ed3-492f82c57116"  => "admin",
		"a3253f9d-0741-4838-8583-20816cd63e11"  => "perusahaan",
		"adc5ce5d-0491-4d88-b9d4-8bc11b40415a"  => "pegawai",
		"ef40c680-03f0-45b9-ab98-290200f5ff13"  => "customer"
	);

	public function index() {
		if($this->session->userdata('email')) {
			if($this->session->userdata('role_id') == array_search('admin', $this->data_role)) {

			}else if($this->session->userdata('role_id') == array_search('perusahaan', $this->data_role)) {
				$perusahaan = $this->db->get_where('perusahaan', ["user_id" => $this->session->userdata('id')])->row_array();
				$data = [
					'title'             => 'Setting Akun Perusahaan',
					'title_main_header' => 'Setting Akun Perusahaan',
					'data_perusahaan'   => $perusahaan,
					'data_perusahaan2'  => $this->session->userdata(),
				];
				if(!isset($_POST['edit_data'])) {
					$this->load->view('account/header', $data);
					$this->load->view('account/navigator', $data);
					$this->load->view('account/main_header', $data);
					$this->load->view('account/setting', $data);
					$this->load->view('account/footer', $data);
				}else{
					$email           = $this->input->post('email');
					$edited_password = $this->input->post('password');
					$new_password    = password_hash($edited_password, PASSWORD_DEFAULT);
					$old_password    = $this->input->post('password_lama');
					// jika password mau diubah
					if($edited_password) {
						if(!$old_password) {
							$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> ganti password, password lama tidak boleh kosong.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
							redirect('perusahaan');
						}else if(password_verify($old_password, $data['data_perusahaan2']['password'])) {
							$this->db->set('password', $new_password);
						}
					}
					$this->db->set('email', $email);
					$this->db->where('id', $data['data_perusahaan2']['id']);
					$up = $this->db->update('users');

					$this->session->set_userdata('email', $email);
					$this->session->set_userdata('password', $new_password);

					$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Akun Perusahaan</strong> berhasil di ubah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('perusahaan');
				}
			}else if($this->session->userdata('role_id') == array_search('pegawai', $this->data_role)) {
				$pegawai = $this->db->get_where('pegawai', ["user_id" => $this->session->userdata('id')])->row_array();
				$data = [
					'title'             => 'Setting Akun pegawai',
					'title_main_header' => 'Setting Akun pegawai',
					'data_pegawai'   => $pegawai,
					'data_pegawai2'  => $this->session->userdata(),
				];
				if(!isset($_POST['edit_data'])) {
					$this->load->view('account/header', $data);
					$this->load->view('account/navigator', $data);
					$this->load->view('account/main_header', $data);
					$this->load->view('account/setting', $data);
					$this->load->view('account/footer', $data);
				}else{
					$email           = $this->input->post('email');
					$edited_password = $this->input->post('password');
					$new_password    = password_hash($edited_password, PASSWORD_DEFAULT);
					$old_password    = $this->input->post('password_lama');
					// jika password mau diubah
					if($edited_password) {
						if(!$old_password) {
							$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> ganti password, password lama tidak boleh kosong.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
							redirect('pegawai');
						}else if(password_verify($old_password, $data['data_pegawai2']['password'])) {
							$this->db->set('password', $new_password);
						}
					}
					$this->db->set('email', $email);
					$this->db->where('id', $data['data_pegawai2']['id']);
					$up = $this->db->update('users');

					$this->session->set_userdata('email', $email);
					$this->session->set_userdata('password', $new_password);

					$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Akun pegawai</strong> berhasil di ubah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('pegawai');
				}
			}else if($this->session->userdata('role_id') == array_search('customer', $this->data_role)) {
				$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
				$data = [
					'title'             => 'Setting Akun customer',
					'title_main_header' => 'Setting Akun customer',
					'data_customer'   => $customer,
					'data_customer2'  => $this->session->userdata(),
				];
				if(!isset($_POST['edit_data'])) {
					$this->load->view('account/header', $data);
					$this->load->view('account/navigator', $data);
					$this->load->view('account/main_header', $data);
					$this->load->view('account/setting', $data);
					$this->load->view('account/footer', $data);
				}else{
					$email           = $this->input->post('email');
					$edited_password = $this->input->post('password');
					$new_password    = password_hash($edited_password, PASSWORD_DEFAULT);
					$old_password    = $this->input->post('password_lama');
					// jika password mau diubah
					if($edited_password) {
						if(!$old_password) {
							$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> ganti password, password lama tidak boleh kosong.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
							redirect('customer');
						}else if(password_verify($old_password, $data['data_customer2']['password'])) {
							$this->db->set('password', $new_password);
						}
					}
					$this->db->set('email', $email);
					$this->db->where('id', $data['data_customer2']['id']);
					$up = $this->db->update('users');

					$this->session->set_userdata('email', $email);
					$this->session->set_userdata('password', $new_password);

					$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Akun customer</strong> berhasil di ubah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('customer');
				}
			}
		}else{
			redirect('auth/login');
		}
	}
}

?>