<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Account extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function index()
	{
		echo 'Hello world!';
	}

}

?>