<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Admin extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function login() {
		if(isset($_POST['login'])) {

		}else{
			$data = [
				'title' => 'Admin'
			];
			$this->load->view('auth/login', $data);
		}
	}

	public function index()
	{
		echo 'Hello world!';
	}

}

?>