<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Auth extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function index()
	{
		echo 'Hello world!';
	}


	private $data_role = array(
		"2c282814-d165-4625-8ed3-492f82c57116"  => "admin",
		"a3253f9d-0741-4838-8583-20816cd63e11"  => "perusahaan",
		"adc5ce5d-0491-4d88-b9d4-8bc11b40415a"  => "pegawai",
		"ef40c680-03f0-45b9-ab98-290200f5ff13"  => "customer"
	);

	public function login() {
		if($this->session->userdata('email')) {
			if($this->session->userdata('role_id') == array_search("perusahaan",$this->data_role)) {
				redirect('perusahaan');
			}else if($this->session->userdata('role_id') == array_search('pegawai', $this->data_role)) {
				redirect('pegawai');
			}
		}else if(!isset($_POST['login'])) {
			$data = [
				'title' => 'User'
			];
			$this->load->view('auth/login', $data);
		}else{
			$email    = $this->input->post('email');
			$password = $this->input->post('password');

			$user = $this->db->get_where('users', ["email" => $email])->row_array();
			if($user) {
				if(password_verify($password, $user["password"])){
					$this->session->set_userdata($user);
					if($user["role_id"] == array_search("perusahaan",$this->data_role)) {
						redirect('perusahaan');
					}else if($user["role_id"] == array_search("pegawai", $this->data_role)) {
						redirect('pegawai');
					}
				}else{
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Password</strong> anda salah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('auth/login');
				}
			}else{
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Email</strong> anda tidak terdaftar.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/login');
			}
		}
	}


	public function logout() {
		$this->session->unset_userdata("id");
		$this->session->unset_userdata("email");
		$this->session->unset_userdata("password");
		$this->session->unset_userdata("role_id");
		$this->session->unset_userdata("is_verified");
		$this->session->unset_userdata("date_joined");
		redirect('auth/login');
	}

	public function perusahaan_register()
	{
		$this->load->view('auth/register_perusahaan');
	}

}

?>