<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Auth extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function index()
	{
		echo 'Hello world!';
	}


	private $data_role = array(
		"2c282814-d165-4625-8ed3-492f82c57116"  => "admin",
		"a3253f9d-0741-4838-8583-20816cd63e11"  => "perusahaan",
		"adc5ce5d-0491-4d88-b9d4-8bc11b40415a"  => "pegawai",
		"ef40c680-03f0-45b9-ab98-290200f5ff13"  => "customer"
	);

	public function login() {
		if($this->session->userdata('email')) {
			if($this->session->userdata('role_id') == array_search("perusahaan",$this->data_role)) {
				redirect('perusahaan');
			}else if($this->session->userdata('role_id') == array_search('pegawai', $this->data_role)) {
				redirect('pegawai');
			}else if($this->session->userdata('role_id') == array_search("admin", $this->data_role)) {
				redirect('admin');
			}else if($this->session->userdata('role_id') == array_search("customer", $this->data_role)) {
				redirect('customer');
			}
		}

		if(!isset($_POST['login'])) {
			$data = [
				'title' => 'User'
			];
			$this->load->view('auth/login', $data);
		}else{
			$email    = $this->input->post('email');
			$password = $this->input->post('password');

			$user = $this->db->get_where('users', ["email" => $email])->row_array();
			if($user) {
				if(password_verify($password, $user["password"])){
					if($user['is_verified'] == 1) {
						if($user['is_blocked'] == 0) {
							$this->session->set_userdata($user);
							if($user["role_id"] == array_search("perusahaan",$this->data_role)) {
								redirect('perusahaan');
							}else if($user["role_id"] == array_search("pegawai", $this->data_role)) {
								redirect('pegawai');
							}else if($user['role_id'] == array_search('admin', $this->data_role)) {
								redirect('admin');
							}else if($user['role_id'] == array_search("customer", $this->data_role)) {
								redirect('customer');
							}
						}else{
							$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Akun anda diblokir</strong> oleh admin, silahkan hubungi customer service.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
							redirect('auth/login');
						}
					}else{
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Akun anda</strong> belum / memang sengaja tidak diverifikasi oleh admin, silahkan hubungi customer service.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/login');
					}
				}else{
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Password</strong> anda salah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('auth/login');
				}
			}else{
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Email</strong> anda tidak terdaftar.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/login');
			}
		}
	}


	public function logout() {
		$this->session->unset_userdata("id");
		$this->session->unset_userdata("email");
		$this->session->unset_userdata("password");
		$this->session->unset_userdata("role_id");
		$this->session->unset_userdata("is_verified");
		$this->session->unset_userdata("date_joined");
		redirect('auth/login');
	}
	public function perusahaan_register()
	{
		if(!isset($_POST['daftar'])) {
		    $this->load->view('auth/register_perusahaan');
		}else{
			$cek_email = $this->db->select('*')->from('users')->where('email', $this->input->post('email'))->get()->row_array();

			if($cek_email) {
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit email, email yang anda masukkan sudah digunakan.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/perusahaan/register');
			}
			$foto_npwp       = '';
			$foto_ktp        = '';
			$logo_perusahaan = '';
			// $upload_logo      = upload("logo_perusahaan","./assets/argon/img/perusahaan/", 'jpg|png|jpeg', 2048, true, base_url().'auth/perusahaan/register');
			// $upload_foto_ktp  = upload("foto_ktp","./assets/argon/img/ktp/", 'jpg|png|jpeg', 2048, true, base_url().'auth/perusahaan/register');
			// $upload_foto_npwp = upload("foto_npwp","./assets/argon/img/npwp/", 'jpg|png|jpeg', 2048, true, base_url().'auth/perusahaan/register');
			
			// if($upload_foto_npwp) {
			// 	$foto_npwp       = $upload_foto_npwp;
			// }

			// if($upload_foto_ktp) {
			// 	$foto_ktp        = $upload_foto_ktp;
			// }

			// if($upload_logo) {
			// 	$logo_perusahaan = $upload_logo;
			// }

			// echo $foto_ktp, $foto_npwp, $logo_perusahaan;

			$edited_perusahaan_logo = $_FILES['logo_perusahaan']['name'];
			$target_dir_perusahaan = "/assets/argon/img/perusahaan/";
			if($edited_perusahaan_logo) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/perusahaan/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('logo_perusahaan')) {
					$new_logo = $this->upload->data('file_name');
					$logo_perusahaan = $new_logo;
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/perusahaan/register');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/perusahaan/register');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			}

			// jika foto npwp diubah
			$target_dir_npwp = FCPATH."assets/argon/img/npwp/";
			$edited_foto_npwp = $_FILES['foto_npwp']['name'];
			if($edited_foto_npwp) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/npwp/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('foto_npwp')) {
					$new_logo  = $this->upload->data('file_name');
					var_dump(copy(FCPATH."assets/argon/img/perusahaan/$new_logo", $target_dir_npwp.$new_logo));
					unlink(FCPATH."assets/argon/img/perusahaan/$new_logo");
					$foto_npwp = $new_logo;
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/perusahaan/register');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/perusahaan/register');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			}

			// jika foto ktp diubah
			$target_dir_ktp = FCPATH."assets/argon/img/ktp/";
			$edited_foto_ktp = $_FILES['foto_ktp']['name'];
			if($edited_foto_ktp) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
;
                $this->session->unset_userdata("email");
                $this->session->unset_userdata("password");
                $this->session->unset_userdata("role_id");
                $this->session->unset_userdata("is_verified");
                $this->session->unset_userdata("date					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/ktp/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('foto_ktp')) {
					$new_logo = $this->upload->data('file_name');
					copy(FCPATH."assets/argon/img/perusahaan/$new_logo", $target_dir_ktp.$new_logo);
					unlink(FCPATH."assets/argon/img/perusahaan/$new_logo");
					$foto_ktp = $new_logo;
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/perusahaan/register');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('auth/perusahaan/register');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			}

			$id_user   = uniqid();
			$data_user = array(
				'id'          => $id_user,
				'email'       => $this->input->post('email'),
				'password'    => password_hash($this->input->post('password'), PASSWORD_DEFAULT),
				'role_id'     => array_search("perusahaan",$this->data_role),
				'is_verified' => 0,
				'date_joined' => formatHariTanggal(date('Y-m-d'))
			);
			$data_perusahaan = array(
				'id'               => uniqid(),
				'nama'  => htmlspecialchars($this->input->post('nama_perusahaan')),
				'nomor_ponsel'     => $this->input->post('nomor_ponsel'),
				'nomor_npwp'       => $this->input->post('nomor_npwp'),
				'foto_npwp'        => $foto_npwp,
				'nomor_ktp'        => $this->input->post('nomor_ktp'),
				'foto_ktp'         => $foto_ktp,
				'user_id'          => $id_user,
				'logo_perusahaan'  => $logo_perusahaan,
				'alamat'           => htmlspecialchars($this->input->post('alamat')),
				'latlon'           => $this->input->post('latlon')
			);

			$this->db->insert('users', $data_user);
			$this->db->insert('perusahaan', $data_perusahaan);
			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Perusahaan anda</strong> berhasil di daftarkan, harap tunggu admin mengkonfirmasi perusahaan anda.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('auth/perusahaan/register');
		}
	}

	public function customer_register()
	{
		if(!isset($_POST['daftar'])) {
			$this->load->view('auth/register_customer');
		}else{
			$cek_email = $this->db->select('*')->from('users')->where('email', $this->input->post('email'))->get()->row_array();

			if($cek_email) {
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit email, email yang anda masukkan sudah digunakan.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/customer/register');
			}
			$foto_ktp                = '';
			$uploaded_foto_ktp       = $_FILES['foto_ktp']['name'];
			$config['upload_path']   = './assets/argon/img/ktp/';
			$config['allowed_types'] = 'jpg|png|jpeg';
			$config['max_size']      = '2048';
			$config['encrypt_name']  = TRUE;

			$this->load->library('upload', $config);

			if($this->upload->do_upload('foto_ktp')) {
				$foto_ktp .= $this->upload->data('file_name');
			}else{
				if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> upload foto pegawai, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('auth/customer/register');
				} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> upload foto pegawai, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('auth/customer/register');
				} else {
					echo $this->upload->display_errors();die;	
				}
			}

			$id_user   = uniqid();
			$data_user = array(
				'id'          => $id_user,
				'email'       => $this->input->post('email'),
				'password'    => password_hash($this->input->post('password'), PASSWORD_DEFAULT),
				'role_id'     => array_search("customer",$this->data_role),
				'is_verified' => 0,
				'date_joined' => formatHariTanggal(date('Y-m-d'))
			);
			$this->db->insert('users', $data_user);
			$data_customer = array(
				'id'            => uniqid(),
				'nama'          => htmlspecialchars($this->input->post('nama_lengkap')),
				'alamat'        => htmlspecialchars($this->input->post('alamat')),
				'nomor_ponsel'  => $this->input->post('nomor_ponsel'),
				'foto_ktp'      => $foto_ktp,
				'nomor_ktp'     => $this->input->post('nomor_ktp'),
				'user_id'       => $data_user['id'],
				'foto_customer' => 'default.png',
				'latlon'        => $this->input->post('latlon')
			);

			// var_dump($data_customer); die;

			$this->db->insert('customer', $data_customer);
			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Akun Anda</strong> berhasil didaftarkan, harap tunggu sampai admin mengkonfirmasi akun anda.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('auth/customer/register');
		}
	}

	public function forgot_password()
	{
		if(!isset($_POST['reset'])) {
			$this->load->view('auth/forgot-password');
		}else{
			list('email' => $email) = $_POST;
			$user = $this->db->get_where('users', ['email' => $email])->row_array();
			if($user) {
				$token      = md5(random_bytes(50));
				$user_token = [
					"email"        => $email,
					"token"        => $token,
					"date_created" => time()
				];
				$this->db->insert('users_token', $user_token);
				$this->_sendEmail($token, 'forgot-password');
				$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert">Silahkan cek email anda untuk <strong>Reset Password</strong> .<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/forgot-password');
			}else{
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Akun Anda</strong> tidak ditemukan, email tidak terdaftar.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/forgot-password');
			}
		}
	}

	public function reset_password()
	{
		$email = $this->input->get('verify');
		$token = $this->input->get('token');

		$user  = $this->db->get_where('users', ['email' => $email])->row_array();

		if($user) {
			$user_token = $this->db->get_where('users_token', ['token' => $token])->row_array();

			if($user_token) {
				if(time() - $user_token['date_created'] < (60*60*24)) {
					$this->session->set_userdata('reset_email', $email);
					$this->changePassword();
				}else{
					$this->db->delete('users', ['email' => $email]);
					$this->db->delete('users_token', ['email' => $email]);
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Reset password gagal</strong> token sudah kedaluwarsa.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('auth/login');
				}
			}else{
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Reset password gagal</strong> token tidak valid.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('auth/login');
			}
		}else{
			$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Reset password gagal</strong> email tidak terdaftar.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('auth/login');
		}
	}

	public function changePassword()
	{
		if(!$this->session->userdata('reset_email')) {
			redirect('auth/login');
		}
		$this->form_validation->set_rules('password', 'Password', 'required|trim|min_length[5]|matches[password2]', [
			'required'   => '%s tidak boleh kosong',
			'min_length' => '%s panjang minimal 5 karakter',
			'matches'    => '%s tidak sama dengan Ulangi Password field'
		]);
		$this->form_validation->set_rules('password2', 'Ulangi Password', 'required|trim|min_length[5]|matches[password]', [
			'required'   => '%s tidak boleh kosong',
			'min_length' => '%s panjang minimal 5 karakter',
			'matches'    => '%s tidak sama dengan Password field'
		]);
		if($this->form_validation->run() == false) {
			$this->load->view('auth/reset-password');
		}else{
			$password = password_hash($this->input->post('password'), PASSWORD_DEFAULT);
			$email    = $this->session->userdata('reset_email');
			$this->session->unset_userdata('reset_email');
			$this->db->delete('users_token', ['email' => $this->input->get('verify')]);
			$this->db->set('password', $password);
			$this->db->where('email', $email);
			$this->db->update('users');
			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Reset password berhasil</strong> silahkan login.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('auth/login');
		}
	}

	private function _sendEmail($token, $type)
	{
		$config = [
			'protocol'    => 'smtp',
			'smtp_host'   => 'ssl://smtp.googlemail.com',
			'smtp_user'   => '' /* Your Email */,
			'smtp_pass'   => '' /* Your email password */,
			'smtp_port'   => 465,
			'mailtype'    => 'html',
			'charset'     => 'utf-8',
			'newline'     => "\r\n"
		];

		$this->load->library('email', $config);
		$this->email->from('fgaming386@gmail.com', 'Muhammad Fauzan W');
		$this->email->to($this->input->post('email'));
		if($type == 'forgot-password') {
			$this->email->subject('Reset Password | Tehniku');
			$this->email->message('Klik link ini untuk merubah password anda : <a href="'. base_url("auth/reset-password?verify=".$this->input->post('email')."&token=".urlencode($token)) .'">Reset</a>');
		}

		if($this->email->send()) {
			return true;
		}else{
			echo $this->email->print_debugger(); die;
		}
	}

}

?>
