<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Customer extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function index()
	{
		checkAuthUser('Customer');
		$perusahaan = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Dashboard',
			'title_main_header' => 'Dashboard',
			'data_customer'   => $perusahaan,
			'data_customer2'  => $this->session->userdata()
		];
		$this->load->view('customer/header', $data);
		$this->load->view('customer/navigator', $data);
		$this->load->view('customer/main_header', $data);
		$this->load->view('customer/index', $data);
		$this->load->view('customer/footer', $data);
	}

	public function pakejasa()
	{
		checkAuthUser('Customer');
		$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Pake Jasa',
			'title_main_header' => 'Pake Jasa',
			'data_customer'     => $customer,
			'data_customer2'    => $this->session->userdata(),
			'data_jasa'         => $this->db->get('jasa')->result_array()
		];
		$this->load->view('customer/header', $data);
		$this->load->view('customer/navigator', $data);
		$this->load->view('customer/main_header', $data);
		$this->load->view('customer/pakejasa', $data);
		$this->load->view('customer/footer', $data);
	}

	public function pakejasa_type($id)
	{
		$type = $this->db->get_where('jasa_pivot_type', ['jasa_id' => $id])->result_array();
		$type = $this->db->from('jasa_pivot_type jpt')->join('jasa j', 'jpt.jasa_id=j.id')->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')->get()->result_array();

		var_dump($type);
	}

	public function setting() 
	{
		checkAuthUser('Customer');
	}

}

?>