<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Customer extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function __construct(){
		parent::__construct();
		checkAuthUser('Customer');
	}

	public function index()
	{
		$perusahaan = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Dashboard',
			'title_main_header' => 'Dashboard',
			'data_customer'   => $perusahaan,
			'data_customer2'  => $this->session->userdata()
		];
		$this->load->view('customer/header', $data);
		$this->load->view('customer/navigator', $data);
		$this->load->view('customer/main_header', $data);
		$this->load->view('customer/index', $data);
		$this->load->view('customer/footer', $data);
	}

	public function pakejasa()
	{
		// echo "<pre>";print_r($data['data_jasa']); die;
		if(isset($_POST['cari_jasa'])) {
			// [$jasa, $latlon] = $_POST;
			list('type_jasa' => $type_jasa, 'keyword_jasa' => $keyword_jasa, 'latlon' => $latlon) = $_POST;
			// echo "<pre>";print_r($_POST); die;
			if($latlon) {
				$this->db
					 ->select('*')
					 ->from('jasa_pivot_type jpt')
					 ->join('jasa j', 'jpt.jasa_id=j.id')
					 ->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')
					 ->join('perusahaan p', 'j.perusahaan_id=p.id')
					 ->join('jasa_keyword jk', 'j.jasa_keyword_id=jk.id');
				if($type_jasa != 'semua_jasa' && $keyword_jasa != 'semua_jasa') {
					$this->db->where('jt.id', $type_jasa);
					$this->db->where('jk.id', $keyword_jasa);
				}else if($type_jasa != 'semua_jasa' && $keyword_jasa == 'semua_jasa') {
					$this->db->where('jt.id', $type_jasa);
				}else if($type_jasa == 'semua_jasa' && $keyword_jasa != 'semua_jasa') {
					$this->db->where('jk.id', $keyword_jasa);
				}
				$data_jasa = $this->db->get()->result_array();
				foreach($data_jasa as $i => $_DATA_JASA) {
					$latlon_perusahaan = explode(", ", $_DATA_JASA['latlon']);
					$latlon_customer   = explode(", ", $latlon);
					$data_jasa[$i]['jarak'] = hitungJarak($latlon_perusahaan[0], $latlon_perusahaan[1],$latlon_customer[0], $latlon_customer[1]);
				}
				sort($data_jasa);
				// echo "<pre>";print_r($data_jasa); die;
				$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
				$data = [
					'title'             => 'Pake Jasa',
					'title_main_header' => 'Pake Jasa',
					'data_customer'     => $customer,
					'data_customer2'    => $this->session->userdata(),
					'data_jasa'         => $data_jasa,
					'data_type_jasa'    => $this->db->get('jasa_type')->result_array(),
					'data_keyword_jasa' => $this->db->get('jasa_keyword')->result_array()
				];
			}else{
				$this->db
					 ->select('j.*, 
								jpt.jasa_id, 
								jpt.jasa_type_id, 
								jt.type, 
								p.nama,
								p.nomor_ponsel,
								p.nomor_npwp,
								p.user_id,
								p.logo_perusahaan,
								p.latlon,
								jk.keyword
					')
					 ->from('jasa_pivot_type jpt')
					 ->join('jasa j', 'jpt.jasa_id=j.id')
					 ->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')
					 ->join('perusahaan p', 'j.perusahaan_id=p.id')
					 ->join('jasa_keyword jk', 'j.jasa_keyword_id=jk.id');
				if($type_jasa != 'semua_jasa' && $keyword_jasa != 'semua_jasa') {
					$this->db->where('jt.id', $type_jasa);
					$this->db->where('jk.id', $keyword_jasa);
				}else if($type_jasa != 'semua_jasa' && $keyword_jasa == 'semua_jasa') {
					$this->db->where('jt.id', $type_jasa);
				}else if($type_jasa == 'semua_jasa' && $keyword_jasa != 'semua_jasa') {
					$this->db->where('jk.id', $keyword_jasa);
				}
				$data_jasa = $this->db->get()->result_array();
				sort($data_jasa);
				// echo "<pre>";print_r($data_jasa); die;
				$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
				$data = [
					'title'             => 'Pake Jasa',
					'title_main_header' => 'Pake Jasa',
					'data_customer'     => $customer,
					'data_customer2'    => $this->session->userdata(),
					'data_jasa'         => $data_jasa,
					'data_type_jasa'    => $this->db->get('jasa_type')->result_array(),
					'data_keyword_jasa' => $this->db->get('jasa_keyword')->result_array()
				];
				foreach($data['data_jasa'] as $i => $_DATA_JASA) {
					$latlon_perusahaan = explode(", ", $_DATA_JASA['latlon']);
					$latlon_customer   = explode(", ", $customer['latlon']);
					$data['data_jasa'][$i]['jarak'] = hitungJarak($latlon_perusahaan[0], $latlon_perusahaan[1],$latlon_customer[0], $latlon_customer[1]);
				}
			}
		}else{
			$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
			$data = [
				'title'             => 'Pake Jasa',
				'title_main_header' => 'Pake Jasa',
				'data_customer'     => $customer,
				'data_customer2'    => $this->session->userdata(),
				'data_jasa'         => $this->db->select('j.*, jpt.jasa_id, jpt.jasa_type_id, jt.type, p.nama,p.nomor_ponsel,p.nomor_npwp,p.user_id,p.logo_perusahaan,p.latlon,jk.keyword')->from('jasa_pivot_type jpt')->join('jasa j', 'jpt.jasa_id=j.id')->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')->join('perusahaan p', 'j.perusahaan_id=p.id')->join('jasa_keyword jk', 'j.jasa_keyword_id=jk.id')->get()->result_array(),
				'data_type_jasa'    => $this->db->get('jasa_type')->result_array(),
				'data_keyword_jasa' => $this->db->get('jasa_keyword')->result_array()
			];
			foreach($data['data_jasa'] as $i => $_DATA_JASA) {
				$latlon_perusahaan = explode(", ", $_DATA_JASA['latlon']);
				$latlon_customer   = explode(", ", $customer['latlon']);
				$data['data_jasa'][$i]['jarak'] = hitungJarak($latlon_perusahaan[0], $latlon_perusahaan[1],$latlon_customer[0], $latlon_customer[1]);
			}
		}
		$this->load->view('customer/header', $data);
		$this->load->view('customer/navigator', $data);
		$this->load->view('customer/main_header', $data);
		$this->load->view('customer/pakejasa', $data);
		$this->load->view('customer/footer', $data);
	}

	public function process_pakejasa($jasa_id) {
		$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$this->db
			 ->select('*')
			 ->from('jasa_pivot_type jpt')
			 ->join('jasa j', 'jpt.jasa_id=j.id')
			 ->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')
			 ->join('jasa_keyword jk', 'j.jasa_keyword_id=jk.id')
			 ->join('perusahaan p', 'j.perusahaan_id=p.id')
			 ->where('j.id', $jasa_id);
		$cekjasa = $this->db->get()->row_array();
		$cektype = $this->db->get_where('jasa_type', ['id' => $_GET['type']])->row_array();
		// $latlon_customer   = explode(", ", );
		// $jarak = openssl_decrypt($_GET['coor'], 'AES-128-CBC', 'T3hn1ku', OPENSSL_RAW_DATA, openssl_random_pseudo_bytes(16));
		// var_dump(base64_decode($_GET['coor'])); die;
		// $jarak = hitungJarak($latlon_perusahaan[0], $latlon_perusahaan[1],$latlon_customer[0], $latlon_customer[1]);
		$data = [
			'title'             => 'Proses Pakejasa',
			'title_main_header' => 'Proses Pakejasa',
			'data_customer'     => $customer,
			'data_customer2'    => $this->session->userdata(),
			'data_jasa'         => $cekjasa,
			'jarak'             => base64_decode($_GET['coor'])
		];
		if(isset($_POST['set_jadwal'])) {
			$split_jadwal = explode(" ", $_POST['jadwal']);
			$pisah        = explode("/", $split_jadwal[1]);
			$jadwal       = formatHariTanggal("$pisah[2]-$pisah[0]-$pisah[1]") . " Jam $split_jadwal[0]";
			$data_pesanan = [
				'id'            => uniqid(),
				'jasa_id'       => $jasa_id,
				'perusahaan_id' => $cekjasa['id'],
				'customer_id'   => $data['data_customer']['id'],
				'waktu'         => $jadwal,
				'description'   => htmlspecialchars($_POST['description']),
				'pegawai_id'    => '',
				'status'        => 1
 			];
			$this->db->insert('pesanan', $data_pesanan);
			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Berhasil</strong> pesan jasa.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('customer/pakejasa/pesanan');
		}else{
			if(isset($_GET['type']) && isset($_GET['coor'])) {
				$this->load->view('customer/header', $data);
				$this->load->view('customer/navigator', $data);
				$this->load->view('customer/main_header', $data);
				$this->load->view('customer/process_pakejasa', $data);
				$this->load->view('customer/footer', $data);
			}else{
				show_404();
			}
		}
	}

	public function pesanan_pakejasa()
	{
		$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$pesanan = $this->db->get('pesanan')->result_array();
		$data_jasa = [];
		foreach($pesanan as $data) {
			$this->db
				 ->select('*')
				 ->from('jasa_pivot_type jpt')
				 ->join('jasa j', 'jpt.jasa_id=j.id')
				 ->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')
				 ->join('perusahaan p', 'j.perusahaan_id=p.id')
				 ->join('jasa_keyword jk', 'j.jasa_keyword_id=jk.id')
				 ->where('jpt.jasa_id', $data['jasa_id']);
			array_push($data_jasa, $this->db->get()->row_array());	
		}
		foreach($data_jasa as $i => $data) {
			$latlon_customer   = explode(", ", $customer['latlon']);
			$latlon_perusahaan = explode(", ", $data['latlon']);
			$data_jasa[$i]['jarak'] = hitungJarak($latlon_perusahaan[0], $latlon_perusahaan[1],$latlon_customer[0], $latlon_customer[1]);
		}
		// echo "<pre>";print_r([$data_jasa, $pesanan]); die;
		$data = [
			'title'             => 'Proses Pakejasa',
			'title_main_header' => 'Proses Pakejasa',
			'data_customer'     => $customer,
			'data_customer2'    => $this->session->userdata(),
			'data_pesanan'      => $pesanan,
			'data_jasa'         => $data_jasa
		];
		$this->load->view('customer/header', $data);
		$this->load->view('customer/navigator', $data);
		$this->load->view('customer/main_header', $data);
		$this->load->view('customer/pesanan', $data);
		$this->load->view('customer/footer', $data);
	}

	public function pesanan_detail_pakejasa($id_pesanan)
	{
		$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$this->db
			 ->select('*')
			 ->from('pesanan ps')
			 ->join('customer c', 'ps.customer_id=c.id')
			 ->join('perusahaan p', 'ps.perusahaan_id=p.id')
			 ->where('ps.id', $id_pesanan);
		$pesanan = $this->db->get()->row_array();
		$this->db
			 ->select('*')
			 ->from('jasa_pivot_type jpt')
			 ->join('jasa j', 'jpt.jasa_id=j.id')
			 ->join('jasa_type jt', 'jpt.jasa_type_id=jt.id')
			 ->join('jasa_keyword jk', 'j.jasa_keyword_id=jk.id')
			 ->where('jpt.jasa_id', $pesanan['jasa_id']);
		$data_jasa = $this->db->get()->row_array();
		$latlon_customer   = explode(", ", $customer['latlon']);
		$latlon_perusahaan = explode(", ", $pesanan['latlon']);
		$data_jasa['jarak'] = hitungJarak($latlon_perusahaan[0], $latlon_perusahaan[1],$latlon_customer[0], $latlon_customer[1]);
		$data = [
			'title'             => 'Detail Pesanan Pakejasa',
			'title_main_header' => 'Detail Pesanan Pakejasa',
			'data_customer'     => $customer,
			'data_customer2'    => $this->session->userdata(),
			'data_pesanan'      => $pesanan,
			'data_jasa'         => $data_jasa
		];
		if($pesanan['status'] == 1) {
			$this->load->view('customer/header', $data);
			$this->load->view('customer/navigator', $data);
			$this->load->view('customer/main_header', $data);
			$this->load->view('customer/wait_verified_pesanan', $data);
			$this->load->view('customer/footer', $data);
		}else if($pesanan['status'] == 2) {
			$this->load->view('customer/header', $data);
			$this->load->view('customer/navigator', $data);
			$this->load->view('customer/main_header', $data);
			$this->load->view('customer/verified_pesanan', $data);
			$this->load->view('customer/footer', $data);
		}
	}

	public function setting() 
	{
		$customer = $this->db->get_where('customer', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Setting',
			'title_main_header' => 'Setting',
			'data_customer'     => $customer,
			'data_customer2'    => $this->session->userdata(),
		];
		if(!isset($_POST['edit_data'])) {
			$this->load->view('customer/header', $data);
			$this->load->view('customer/navigator', $data);
			$this->load->view('customer/main_header', $data);
			$this->load->view('customer/setting', $data);
			$this->load->view('customer/footer', $data);
		}else{
			list('nama' => $nama, 'email' => $email, 'new_password' => $edited_password, 'old_password' => $old_password, 'nomor_ponsel' => $nomor_ponsel) = $_POST;
			$new_password    = password_hash($edited_password, PASSWORD_DEFAULT);
			$data_customer   = $this->db->get_where('users', ['id' => $this->session->userdata('id')])->row_array();
			$cek_email       = $this->db->select('*')->from('users')->where_not_in('email', $data['data_customer2']['email'])->where('email', $email)->get()->row_array();

			if($cek_email) {
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit email, email yang anda masukkan sudah digunakan.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('customer');
			}
			$edited_foto     = $_FILES['foto_customer']['name'];
			// jika password mau diubah
			if($edited_password) {
				if(!$old_password) {
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> ganti password, password lama tidak boleh kosong.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('customer');
				}else {
					if(password_verify($old_password, $data_customer['password'])) {
						$this->db->set('password', $new_password);
					}else{
						// echo $old_password."<br><br>",
						// $data['data_customer2']['password']."<br><br>";
						// echo password_verify($old_password, $data['data_customer2']['password']); die;
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> ganti password, password lama salah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('customer');
					}
				}
			}
			$this->db->set('email', $email);
			$this->db->where('id', $data['data_customer2']['id']);
			$this->db->update('users');

			if($edited_foto) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/customer/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('foto_customer')) {
					$new_logo = $this->upload->data('file_name');
					if($data['data_customer']['foto_customer'] != 'default.png') {
						unlink(FCPATH."assets/argon/img/customer/".$data['data_customer']['foto_customer']);
					}
					$this->db->set('foto_customer', $new_logo);
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit foto, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('customer');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit foto, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('customer');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			} 
			$this->db->set('nama', $nama);
			$this->db->set('nomor_ponsel', $nomor_ponsel);
			$this->db->update('customer');

			$this->session->set_userdata('email', $email);
			$this->session->set_userdata('password', $new_password);

			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Akun Customer</strong> berhasil di ubah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('customer');
		}
	}

}

?>