<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Landing extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	public function index()
	{
		$this->load->view('Landing/index');
	}

}

?>