<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Pegawai extends CI_Controller {

	/**
	*	 Generated by Generator
	**/

	private $data_role = array(
		"2c282814-d165-4625-8ed3-492f82c57116"  => "admin",
		"a3253f9d-0741-4838-8583-20816cd63e11"  => "perusahaan",
		"adc5ce5d-0491-4d88-b9d4-8bc11b40415a"  => "pegawai",
		"ef40c680-03f0-45b9-ab98-290200f5ff13"  => "customer"
	);

	public function __construct() {
		parent::__construct();
		if(!$this->session->userdata('email')) {
			redirect('auth/login');
		}elseif($this->session->userdata('email') && $this->session->userdata('role_id') != array_search("pegawai",$this->data_role)) {
			show_404();
		}
	}

	public function index()
	{
		$pegawai    = $this->db->get_where('pegawai', ["user_id" => $this->session->userdata('id')])->row_array();
		$perusahaan = $this->db->get_where('perusahaan', ["id" => $pegawai['perusahaan_id']])->row_array();
		$data = [
			'title'             => 'Dashboard',
			'title_main_header' => 'Dashboard',
			'data_pegawai'      => $pegawai,
			'data_perusahaan'   => $perusahaan,
			'data_pegawai2'     => $this->session->userdata()
		];
		$this->load->view('pegawai/header', $data);
		$this->load->view('pegawai/navigator', $data);
		$this->load->view('pegawai/main_header', $data);
		$this->load->view('pegawai/index', $data);
		$this->load->view('pegawai/footer', $data);
	}

}

?>