<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Perusahaan extends CI_Controller {

	/**
	*	 Generated by Generator
	**/
	private $data_role = array(
		"2c282814-d165-4625-8ed3-492f82c57116"  => "admin",
		"a3253f9d-0741-4838-8583-20816cd63e11"  => "perusahaan",
		"adc5ce5d-0491-4d88-b9d4-8bc11b40415a"  => "pegawai",
		"ef40c680-03f0-45b9-ab98-290200f5ff13"  => "customer"
	);

	public function __construct() {
		parent::__construct();
		if(!$this->session->userdata('email')) {
			redirect('auth/login');
		}elseif($this->session->userdata('email') && $this->session->userdata('role_id') != array_search("perusahaan",$this->data_role)) {
			show_404();
		}
	}

	public function index()
	{
		$perusahaan = $this->db->get_where('perusahaan', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Dashboard',
			'title_main_header' => 'Dashboard',
			'data_perusahaan'   => $perusahaan,
			'data_perusahaan2'  => $this->session->userdata()
		];
		$this->load->view('perusahaan/header', $data);
		$this->load->view('perusahaan/navigator', $data);
		$this->load->view('perusahaan/main_header', $data);
		$this->load->view('perusahaan/index', $data);
		$this->load->view('perusahaan/footer', $data);
	}

	public function manage() {
		$perusahaan = $this->db->get_where('perusahaan', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Manage',
			'title_main_header' => 'Manage Perusahaan',
			'data_perusahaan'   => $perusahaan,
			'data_perusahaan2'  => $this->session->userdata()
		];
		if(isset($_POST['manage'])) {


			// jika logo perusahaan diubah
			$edited_perusahaan_logo = $_FILES['logo_perusahaan']['name'];
			if($edited_perusahaan_logo) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/perusahaan/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('logo_perusahaan')) {
					$new_logo = $this->upload->data('file_name');
					unlink(FCPATH."assets/argon/img/perusahaan/".$data['data_perusahaan']['logo_perusahaan']);
					$this->db->set('logo_perusahaan', $new_logo);
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('perusahaan');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('perusahaan');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			}

			// jika foto npwp diubah
			$edited_foto_npwp = $_FILES['foto_npwp']['name'];
			if($edited_foto_npwp) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/npwp/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('foto_npwp')) {
					$new_logo = $this->upload->data('file_name');
					unlink(FCPATH."assets/argon/img/npwp/".$data['data_perusahaan']['foto_npwp']);
					$this->db->set('foto_npwp', $new_logo);
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('perusahaan');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('perusahaan');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			}

			// jika foto ktp diubah
			$edited_foto_ktp = $_FILES['foto_ktp']['name'];
			if($edited_foto_ktp) {
				$config = array(
					'allowed_types' => 'jpeg|jpg|png',
					'max_size'      => '2048',
					'upload_path'   => './assets/argon/img/ktp/',
					'encrypt_name'  => TRUE
				);
				$this->load->library('upload', $config);

				if($this->upload->do_upload('foto_ktp')) {
					$new_logo = $this->upload->data('file_name');
					unlink(FCPATH."assets/argon/img/ktp/".$data['data_perusahaan']['foto_ktp']);
					$this->db->set('foto_ktp', $new_logo);
				}else{
					if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('perusahaan');
					} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
						$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> edit logo perusahaan, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
						redirect('perusahaan');
					} else {
						echo $this->upload->display_errors();die;	
					}
				}
			}
			$this->db->set('nama_perusahaan', htmlspecialchars($this->input->post('nama_perusahaan')));
			$this->db->set('alamat', htmlspecialchars($this->input->post('alamat')));
			$this->db->set('nomor_npwp', $this->input->post('nomor_npwp'));
			$this->db->set('nomor_ktp', $this->input->post('nomor_ktp'));
			$this->db->set('latlon', $this->input->post('latlon'));
			$this->db->where('id', $data['data_perusahaan']['id']);
			$this->db->update('perusahaan');
			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Data Perusahaan</strong> berhasil di ubah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('perusahaan');
		}else{
			$data['data_jasa'] = $this->db->get_where('jasa', ['perusahaan_id' => $data['data_perusahaan']['id']])->result_array();
			$this->load->view('perusahaan/header', $data);
			$this->load->view('perusahaan/navigator', $data);
			$this->load->view('perusahaan/main_header', $data);
			$this->load->view('perusahaan/manage_perusahaan', $data);
			$this->load->view('perusahaan/footer', $data);
		}
	}

	public function pegawai() {
		$perusahaan = $this->db->get_where('perusahaan', ["user_id" => $this->session->userdata('id')])->row_array();
		$pegawai    = $this->db->get("pegawai")->result_array();
		$data = [
			'title'             => 'Pegawai',
			'title_main_header' => 'Pegawai '.$perusahaan['nama_perusahaan'],
			'data_perusahaan'   => $perusahaan,
			'data_perusahaan2'  => $this->session->userdata(),
			"data_pegawai"      => $pegawai
		];
		$this->load->view('perusahaan/header', $data);
		$this->load->view('perusahaan/navigator', $data);
		$this->load->view('perusahaan/main_header', $data);
		$this->load->view('perusahaan/pegawai', $data);
		$this->load->view('perusahaan/footer', $data);
	}

	public function tambah_pegawai() {
		$perusahaan = $this->db->get_where('perusahaan', ["user_id" => $this->session->userdata('id')])->row_array();
		$pegawai    = $this->db->get("pegawai")->result_array();
		if(!isset($_POST['tambah_pegawai'])) {
			$data = [
				'title'             => 'Pegawai',
				'title_main_header' => 'Pegawai '.$perusahaan['nama_perusahaan'],
				'data_perusahaan'   => $perusahaan,
				'data_perusahaan2'  => $this->session->userdata(),
				"data_pegawai"      => $pegawai
			];
			$this->load->view('perusahaan/header', $data);
			$this->load->view('perusahaan/navigator', $data);
			$this->load->view('perusahaan/main_header', $data);
			$this->load->view('perusahaan/tambah_pegawai', $data);
			$this->load->view('perusahaan/footer', $data);
		}else{
			$upload_image = $_FILES['foto_pegawai']['name'];
			$config['upload_path']   = './assets/argon/img/pegawai/';
			$config['allowed_types'] = 'jpg|png|jpeg';
			$config['max_size']      = '2048';
			$config['encrypt_name']  = TRUE;

			$this->load->library('upload', $config);

			if($this->upload->do_upload('foto_pegawai')) {
				$new_image = $this->upload->data('file_name');
				$user_id = uniqid();
				$data_user = [
					"id"           => $user_id,
					"email"        => $this->input->post('email'),
					"password"     => password_hash($this->input->post('password'), PASSWORD_DEFAULT),
					"role_id"      => array_search("pegawai",$this->data_role),
					"is_verified"  => 1,
					"date_joined"  => formatHariTanggal(date('Y-m-d'))
				];
				$data_pegawai = [
					"id"            => uniqid(),
					"nama"          => htmlspecialchars($this->input->post('nama')),
					"umur"          => $this->input->post('umur'),
					"nomor_ponsel"  => $this->input->post('nomor_ponsel'),
					"nomor_ktp"     => $this->input->post('nomor_ktp'),
					"gender"        => $this->input->post('gender'),
					"perusahaan_id" => $perusahaan['id'],
					"user_id"       => $user_id,
					"foto_pegawai"  => $new_image,
					"status"        => 1
				];
				$addUser    = $this->db->insert('users', $data_user);
				$addPegawai = $this->db->insert('pegawai', $data_pegawai);
				if(!$addUser || !$addPegawai) {
					unlink(BASEPATH."../assets/argon/img/pegawai/".$new_image);
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> tambah pegawai.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('perusahaan/pegawai');
				}else{
					$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Berhasil</strong> tambah pegawai.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('perusahaan/pegawai');
				}
			}else{
				if($this->upload->display_errors() == "<p>The filetype you are attempting to upload is not allowed.</p>") {
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> upload foto pegawai, format foto harus jpg / png /jpeg.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('perusahaan/pegawai');
				} else if($this->upload->display_errors() == "<p>The file you are attempting to upload is larger than the permitted size.</p>") {
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> upload foto pegawai, size foto tidak boleh lebih dari 2mb.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('perusahaan/pegawai');
				} else {
					echo $this->upload->display_errors();die;	
				}
			}
		}
	}

	public function hapus_pegawai($id) {
		$cek = $this->db->get_where('pegawai', ['id' => $id])->row_array();
		if($cek) {
			$hapus = $this->db->delete('pegawai', ['id' => $id]);
			if($hapus){
				unlink(BASEPATH."../assets/argon/img/pegawai/".$cek['foto_pegawai']);
				$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Berhasil</strong> hapus data pegawai.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
				redirect('perusahaan/pegawai');
			}else{
				$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Gagal</strong> hapus pegawai.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('perusahaan/pegawai');
			}
		}else{
			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Gagal</strong> hapus, pegawai tidak terdaftar.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('perusahaan/pegawai');
		}
	}

	public function setting() {
		$perusahaan = $this->db->get_where('perusahaan', ["user_id" => $this->session->userdata('id')])->row_array();
		$data = [
			'title'             => 'Setting Akun Perusahaan',
			'title_main_header' => 'Setting Akun Perusahaan',
			'data_perusahaan'   => $perusahaan,
			'data_perusahaan2'  => $this->session->userdata(),
		];
		if(!isset($_POST['edit_data'])) {
			$this->load->view('perusahaan/header', $data);
			$this->load->view('perusahaan/navigator', $data);
			$this->load->view('perusahaan/main_header', $data);
			$this->load->view('perusahaan/setting', $data);
			$this->load->view('perusahaan/footer', $data);
		}else{
			$email           = $this->input->post('email');
			$edited_password = $this->input->post('password');
			$new_password    = password_hash($edited_password, PASSWORD_DEFAULT);
			$old_password    = $this->input->post('password_lama');
			// jika password mau diubah
			if($edited_password) {
				if(!$old_password) {
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Gagal</strong> ganti password, password lama tidak boleh kosong.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
					redirect('perusahaan');
				}else if(password_verify($old_password, $data['data_perusahaan2']['password'])) {
					$this->db->set('password', $new_password);
				}
			}
			$this->db->set('email', $email);
			$this->db->where('id', $data['data_perusahaan2']['id']);
			$up = $this->db->update('users');

			$this->session->set_userdata('email', $email);
			$this->session->set_userdata('password', $new_password);

			$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>Akun Perusahaan</strong> berhasil di ubah.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
			redirect('perusahaan');
		}
	}

}

?>